name: magtense-env
channels:
  - https://software.repos.intel.com/python/conda
  - https://software.repos.intel.com/python/conda/
  - nvidia/label/cuda-12.6.3
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - meson
  - charset-normalizer
  - git
  - notebook
  - h5py
  - tqdm
  - mkl-devel
  - mkl-include
  - mkl-static
  - dpcpp-cpp-rt
  - intel-fortran-rt
  - ifx_win-64
  - make
